--Patrick Warren
--CIS310-01
--A10BB
--Stored procedure for the star schema
ALTER PROCEDURE [dbo].[A10BB]
AS
BEGIN
	
	--DROP ALL CONSTRAINTS
	ALTER TABLE FACT
	DROP CONSTRAINT PK_FACT,
		CONSTRAINT FK_FACT_PRODUCTDIM,
		CONSTRAINT FK_FACT_CUSTMERDIM,
		CONSTRAINT FK_FACT_TIMEDIM,
		CONSTRAINT FK_FACT_EMPLOYEEDIM

	ALTER TABLE PRODUCTDIM
		DROP CONSTRAINT PK_PRODUCTDIM

	ALTER TABLE CUSTOMERDIM
		DROP CONSTRAINT PK_CUSTOMERDIM

	ALTER TABLE TIMEDIM
		DROP CONSTRAINT PK_TIMEID

	ALTER TABLE EMPLOYEEDIM
		DROP CONSTRAINT PK_EMPLOYEEID

	--TRUNCATE ALL TABLES
	TRUNCATE TABLE PRODUCTDIM
	TRUNCATE TABLE CUSTOMERDIM
	TRUNCATE TABLE TIMEDIM
	TRUNCATE TABLE EMPLOYEEDIM
	TRUNCATE TABLE FACT
	TRUNCATE TABLE STAGING

	--ADD CONSTRAINTS BACK TO TABLES
	ALTER TABLE PRODUCTDIM
		ADD CONSTRAINT PK_PRODUCTDIM PRIMARY KEY (PRODUCTID)

	ALTER TABLE CUSTOMERDIM
		ADD CONSTRAINT PK_CUSTOMERDIM PRIMARY KEY (CUSTOMERID)

	ALTER TABLE TIMEDIM
		ADD CONSTRAINT PK_TIMEID PRIMARY KEY (TIMEID)

	ALTER TABLE EMPLOYEEDIM
		ADD CONSTRAINT PK_EMPLOYEEID PRIMARY KEY (EMPLOYEEID)

	ALTER TABLE FACT
		ADD CONSTRAINT PK_FACT PRIMARY KEY (PRODUCTID, CUSTOMERID, TIMEID, EMPLOYEEID),
			CONSTRAINT FK_FACT_PRODUCTDIM FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTDIM,
			CONSTRAINT FK_FACT_CUSTMERDIM FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMERDIM,
			CONSTRAINT FK_FACT_TIMEDIM	FOREIGN KEY (TIMEID) REFERENCES TIMEDIM,
			CONSTRAINT FK_FACT_EMPLOYEEDIM FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEEDIM

	--INSERT VALUES INTO DIMENSION TABLES AND STAGING TABLE
	INSERT INTO PRODUCTDIM
	SELECT	P.PROD_SKU, P.PROD_DESCRIPT, P.PROD_TYPE,
			B.BRAND_ID, B.BRAND_NAME, B.BRAND_TYPE
	FROM	LGPRODUCT P INNER JOIN LGBRAND B ON P.BRAND_ID = B.BRAND_ID

	INSERT INTO CUSTOMERDIM
	SELECT	CUST_CODE, CUST_FNAME, CUST_LNAME, CUST_CITY, CUST_STATE, CUST_ZIP
	FROM	LGCUSTOMER

	INSERT INTO TIMEDIM
	SELECT	INV_DATE, YEAR(INV_DATE), MONTH(INV_DATE), DATEPART(QQ, INV_DATE)
	FROM	LGINVOICE

	INSERT INTO EMPLOYEEDIM
	SELECT	E.EMP_NUM, E.EMP_FNAME, E.EMP_LNAME, E.EMP_TITLE, D.DEPT_NUM, D.DEPT_NAME
	FROM	LGEMPLOYEE E INNER JOIN LGDEPARTMENT D ON E.DEPT_NUM = D.DEPT_NUM
	
	INSERT INTO STAGING (LINE_QTY, LINE_PRICE, EMP_NUM, INV_DATE, CUST_CODE, PROD_SKU)
	SELECT	LL.LINE_QTY, LL.LINE_PRICE, 
			LE.EMP_NUM, LI.INV_DATE, LC.CUST_CODE, LP.PROD_SKU
	FROM	LGLINE LL INNER JOIN LGINVOICE LI ON LL.INV_NUM = LI.INV_NUM
			INNER JOIN LGCUSTOMER LC ON LC.CUST_CODE = LI.CUST_CODE
			INNER JOIN LGEMPLOYEE LE ON LE.EMP_NUM = LI.EMPLOYEE_ID
			INNER JOIN LGPRODUCT LP ON LP.PROD_SKU = LL.PROD_SKU


	UPDATE STAGING
	SET		CUSTOMERID = CD.CUSTOMERID
	FROM	STAGING S INNER JOIN CUSTOMERDIM CD ON S.CUST_CODE = CD.CUST_CODE

	UPDATE STAGING
	SET		PRODUCTID = PD.PRODUCTID
	FROM	STAGING S INNER JOIN PRODUCTDIM PD ON PD.PROD_SKU = S.PROD_SKU

	UPDATE STAGING
	SET		TIMEID = TD.TIMEID
	FROM	STAGING S INNER JOIN TIMEDIM TD ON TD.INV_DATE = S.INV_DATE

	UPDATE STAGING
	SET		EMPLOYEEID = ED.EMPLOYEEID
	FROM	STAGING S INNER JOIN EMPLOYEEDIM ED ON ED.EMP_NUM = S.EMP_NUM

	INSERT INTO FACT
	SELECT	PRODUCTID, TIMEID, CUSTOMERID, EMPLOYEEID, SUM(LINE_QTY), AVG(LINE_PRICE)
	FROM	STAGING
	GROUP BY PRODUCTID, TIMEID, CUSTOMERID, EMPLOYEEID


END
GO

--EXECUTE THE STORED PROCEDURE
EXEC dbo.A10BB;