--Patrick Warren
--CIS310-01
--A10BC
--Queries to test the stored procedUre.

--RUN STORED PROCEDURE
EXEC dbo.A10BB

--What are the top 5 products in terms of sales (total quantity * price)?
SELECT	F.PRODUCTID, PD.PROD_SKU, PD.PROD_DESCRIPT, SUM(F.LINE_PRICE*F.LINE_QTY) AS TOTAL
FROM	FACT F INNER JOIN PRODUCTDIM PD ON PD.PRODUCTID = F.PRODUCTID
GROUP BY	F.PRODUCTID, PD.PROD_SKU, PD.PROD_DESCRIPT
HAVING	SUM(F.LINE_PRICE*F.LINE_QTY) IN (SELECT	TOP 5 SUM(F.LINE_QTY*F.LINE_PRICE) AS TOTAL
										FROM	FACT F INNER JOIN PRODUCTDIM PD ON F.PRODUCTID = PD.PRODUCTID
										GROUP BY PD.PROD_SKU
										ORDER BY TOTAL DESC)
ORDER BY TOTAL DESC

--List the names of employees who have sold the most products in terms of amount of sales (total of quantity * price).
SELECT	ED.EMP_FNAME, ED.EMP_LNAME, SUM(F.LINE_QTY*F.LINE_PRICE) AS TOTAL
FROM	FACT F INNER JOIN EMPLOYEEDIM ED ON F.EMPLOYEEID = ED.EMPLOYEEID
GROUP BY ED.EMP_FNAME, ED.EMP_LNAME
HAVING	SUM(F.LINE_PRICE*F.LINE_QTY) IN (SELECT	TOP 5 SUM(F.LINE_QTY*F.LINE_PRICE) AS TOTAL
										FROM	FACT F INNER JOIN EMPLOYEEDIM ED ON F.EMPLOYEEID = ED.EMPLOYEEID
										GROUP BY ED.EMP_FNAME, ED.EMP_LNAME
										ORDER BY TOTAL DESC)
ORDER BY TOTAL DESC

--List the total amount of sales by customer city and brand name. 
SELECT	CD.CUST_CITY, PD.BRAND_NAME, SUM(F.LINE_QTY*F.LINE_PRICE) AS TOTAL
FROM	FACT F INNER JOIN CUSTOMERDIM CD ON F.CUSTOMERID = CD.CUSTOMERID
		INNER JOIN PRODUCTDIM PD ON F.PRODUCTID = PD.PRODUCTID
GROUP BY CD.CUST_CITY, PD.BRAND_NAME
ORDER BY TOTAL DESC

--List the customer names of customers and top 5 products each of these customers have bought
SELECT	CD.CUST_FNAME, CD.CUST_LNAME, PD.PROD_SKU, SUM(F.LINE_QTY*F.LINE_PRICE) AS TOTAL
FROM	FACT F INNER JOIN CUSTOMERDIM CD ON F.CUSTOMERID = CD.CUSTOMERID
		INNER JOIN PRODUCTDIM PD ON F.PRODUCTID = PD.PRODUCTID
GROUP BY CD.CUSTOMERID, CD.CUST_FNAME, CD.CUST_LNAME, PD.PROD_SKU
HAVING	SUM(F.LINE_PRICE*F.LINE_QTY) IN (SELECT	TOP 5 SUM(F.LINE_QTY*F.LINE_PRICE) AS TOTAL
										FROM	FACT F INNER JOIN CUSTOMERDIM CD ON F.CUSTOMERID = CD.CUSTOMERID
														INNER JOIN PRODUCTDIM PD ON F.PRODUCTID = PD.PRODUCTID
										GROUP BY CD.CUSTOMERID, CD.CUST_FNAME, CD.CUST_LNAME, PD.PROD_SKU
										ORDER BY CD.CUST_LNAME, TOTAL DESC
										)
ORDER BY CD.CUST_LNAME, TOTAL DESC